/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AddComment200Data } from './addComment200Data';

export type AddComment200 = {
  success: boolean;
  message: string;
  data: AddComment200Data;
};
