/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AddPost200Data } from './addPost200Data';

export type AddPost200 = {
  success: true;
  message: string;
  data: AddPost200Data;
};
