/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AuthLogin200DataAvatarUrl } from './authLogin200DataAvatarUrl';
import type { AuthLogin200DataCreatedAt } from './authLogin200DataCreatedAt';
import type { AuthLogin200DataUpdatedAt } from './authLogin200DataUpdatedAt';

export type AuthLogin200Data = {
  id: string;
  email: string;
  name: string;
  username: string;
  /** @nullable */
  avatarUrl: AuthLogin200DataAvatarUrl;
  createdAt: AuthLogin200DataCreatedAt;
  updatedAt: AuthLogin200DataUpdatedAt;
};
