/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AuthMe200Data } from './authMe200Data';

export type AuthMe200 = {
  success: boolean;
  message: string;
  data: AuthMe200Data;
};
