/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AuthRegister200Data } from './authRegister200Data';

export type AuthRegister200 = {
  success: true;
  message: string;
  data: AuthRegister200Data;
};
