/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AuthRefreshTokens200Data } from './authRefreshTokens200Data';

export type AuthRefreshTokens200 = {
  success: boolean;
  message: string;
  data: AuthRefreshTokens200Data;
};
