/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { DeleteCommentsByCommentId200DataCreatedAt } from './deleteCommentsByCommentId200DataCreatedAt';
import type { DeleteCommentsByCommentId200DataUpdatedAt } from './deleteCommentsByCommentId200DataUpdatedAt';

export type DeleteCommentsByCommentId200Data = {
  id: number;
  message: string;
  userId: string;
  postId: string;
  createdAt: DeleteCommentsByCommentId200DataCreatedAt;
  updatedAt: DeleteCommentsByCommentId200DataUpdatedAt;
};
