/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { DeleteCommentsByCommentId200Data } from './deleteCommentsByCommentId200Data';

export type DeleteCommentsByCommentId200 = {
  success: boolean;
  message: string;
  data: DeleteCommentsByCommentId200Data;
};
