/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetCommentsShowByCommentId200DataCreatedAt } from './getCommentsShowByCommentId200DataCreatedAt';
import type { GetCommentsShowByCommentId200DataUpdatedAt } from './getCommentsShowByCommentId200DataUpdatedAt';

export type GetCommentsShowByCommentId200Data = {
  id: number;
  message: string;
  userId: string;
  postId: string;
  createdAt: GetCommentsShowByCommentId200DataCreatedAt;
  updatedAt: GetCommentsShowByCommentId200DataUpdatedAt;
};
