/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetCommentsShowByCommentId200Data } from './getCommentsShowByCommentId200Data';

export type GetCommentsShowByCommentId200 = {
  success: true;
  message: string;
  data: GetCommentsShowByCommentId200Data;
};
