/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListPosts200DataItem } from './listPosts200DataItem';

export type ListPosts200 = {
  success: true;
  message: string;
  data: ListPosts200DataItem[];
};
