/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListComments200DataItem } from './listComments200DataItem';

export type ListComments200 = {
  success: boolean;
  message: string;
  data: ListComments200DataItem[];
};
