/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PatchCommentsByCommentId200Data } from './patchCommentsByCommentId200Data';

export type PatchCommentsByCommentId200 = {
  success: true;
  message: string;
  data: PatchCommentsByCommentId200Data;
};
