/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemoveComment200Data } from './removeComment200Data';

export type RemoveComment200 = {
  success: boolean;
  message: string;
  data: RemoveComment200Data;
};
