/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemoveComment200DataCreatedAt } from './removeComment200DataCreatedAt';
import type { RemoveComment200DataUpdatedAt } from './removeComment200DataUpdatedAt';

export type RemoveComment200Data = {
  id: number;
  message: string;
  userId: string;
  postId: string;
  createdAt: RemoveComment200DataCreatedAt;
  updatedAt: RemoveComment200DataUpdatedAt;
};
