/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemovePost200DataThumbnailUrl } from './removePost200DataThumbnailUrl';
import type { RemovePost200DataCreatedAt } from './removePost200DataCreatedAt';
import type { RemovePost200DataUpdatedAt } from './removePost200DataUpdatedAt';

export type RemovePost200Data = {
  id: string;
  title: string;
  content: string;
  /** @nullable */
  thumbnailUrl: RemovePost200DataThumbnailUrl;
  authorId: string;
  createdAt: RemovePost200DataCreatedAt;
  updatedAt: RemovePost200DataUpdatedAt;
};
