/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { RemovePost200Data } from './removePost200Data';

export type RemovePost200 = {
  success: boolean;
  message: string;
  data: RemovePost200Data;
};
