/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ShowPost200Data } from './showPost200Data';

export type ShowPost200 = {
  success: boolean;
  message: string;
  data: ShowPost200Data;
};
