/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { UpdatePost200DataThumbnailUrl } from './updatePost200DataThumbnailUrl';

export type UpdatePost200Data = {
  id: string;
  title: string;
  content: string;
  /** @nullable */
  thumbnailUrl: UpdatePost200DataThumbnailUrl;
  authorId: string;
  createdAt: string;
  updatedAt: string;
};
