/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { UpdateComment200Data } from './updateComment200Data';

export type UpdateComment200 = {
  success: boolean;
  message: string;
  data: UpdateComment200Data;
};
