/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { UpdatePost200Data } from './updatePost200Data';

export type UpdatePost200 = {
  success: true;
  message: string;
  data: UpdatePost200Data;
};
