/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { UpdateComment200DataCreatedAt } from './updateComment200DataCreatedAt';
import type { UpdateComment200DataUpdatedAt } from './updateComment200DataUpdatedAt';

export type UpdateComment200Data = {
  id: number;
  message: string;
  userId: string;
  postId: string;
  createdAt: UpdateComment200DataCreatedAt;
  updatedAt: UpdateComment200DataUpdatedAt;
};
