/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';


/**
 * add new commnet for this post
 * @summary add
 */
export const addCommentParams = zod.object({
  "postId": zod.string()
})

export const addCommentBody = zod.object({
  "content": zod.string()
})

/**
 * list comments of a post
 * @summary list
 */
export const listCommentsParams = zod.object({
  "postId": zod.uuid(),
  "userId": zod.uuid()
})

/**
 * Comments Endpoints
 * @summary show
 */
export const getCommentsShowByCommentIdParams = zod.object({
  "commentId": zod.number()
})

/**
 * Comments Endpoints
 * @summary update
 */
export const patchCommentsByCommentIdParams = zod.object({
  "commentId": zod.number()
})

export const patchCommentsByCommentIdBody = zod.object({
  "message": zod.string()
})

/**
 * Comments Endpoints
 * @summary remove
 */
export const deleteCommentsByCommentIdParams = zod.object({
  "commentId": zod.number()
})

