/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  AddComment200,
  AddComment400,
  AddComment401,
  AddComment403,
  AddComment404,
  AddComment409,
  AddComment422,
  AddComment500,
  AddCommentBodyOne,
  AddCommentBodyThree,
  AddCommentBodyTwo,
  DeleteCommentsByCommentId200,
  DeleteCommentsByCommentId400,
  DeleteCommentsByCommentId401,
  DeleteCommentsByCommentId403,
  DeleteCommentsByCommentId404,
  DeleteCommentsByCommentId409,
  DeleteCommentsByCommentId422,
  DeleteCommentsByCommentId500,
  GetCommentsShowByCommentId200,
  GetCommentsShowByCommentId400,
  GetCommentsShowByCommentId401,
  GetCommentsShowByCommentId403,
  GetCommentsShowByCommentId404,
  GetCommentsShowByCommentId409,
  GetCommentsShowByCommentId422,
  GetCommentsShowByCommentId500,
  ListComments200,
  ListComments400,
  ListComments401,
  ListComments403,
  ListComments404,
  ListComments409,
  ListComments422,
  ListComments500,
  PatchCommentsByCommentId200,
  PatchCommentsByCommentId400,
  PatchCommentsByCommentId401,
  PatchCommentsByCommentId403,
  PatchCommentsByCommentId404,
  PatchCommentsByCommentId409,
  PatchCommentsByCommentId422,
  PatchCommentsByCommentId500,
  PatchCommentsByCommentIdBodyOne,
  PatchCommentsByCommentIdBodyThree,
  PatchCommentsByCommentIdBodyTwo
} from '.././schemas';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * add new commnet for this post
 * @summary add
 */
export const addComment = (
    postId: string,
    addCommentBody: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AddComment200>(
      {url: `http://localhost:4000/comments/${postId}`, method: 'POST',
      data: addCommentBody, signal
    },
      options);
    }
  


export const getAddCommentMutationOptions = <TError = AddComment400 | AddComment401 | AddComment403 | AddComment404 | AddComment409 | AddComment422 | AddComment500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree}, TContext> => {

const mutationKey = ['addComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addComment>>, {postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree}> = (props) => {
          const {postId,data} = props ?? {};

          return  addComment(postId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddCommentMutationResult = NonNullable<Awaited<ReturnType<typeof addComment>>>
    export type AddCommentMutationBody = AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree
    export type AddCommentMutationError = AddComment400 | AddComment401 | AddComment403 | AddComment404 | AddComment409 | AddComment422 | AddComment500

    /**
 * @summary add
 */
export const createAddComment = <TError = AddComment400 | AddComment401 | AddComment403 | AddComment404 | AddComment409 | AddComment422 | AddComment500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof addComment>>,
        TError,
        {postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree},
        TContext
      > => {

      const mutationOptions = getAddCommentMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * list comments of a post
 * @summary list
 */
export const listComments = (
    postId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListComments200>(
      {url: `http://localhost:4000/comments/${postId}`, method: 'GET', signal
    },
      options);
    }
  



export const getListCommentsQueryKey = (postId?: string,) => {
    return [
    `http://localhost:4000/comments/${postId}`
    ] as const;
    }

    
export const getListCommentsQueryOptions = <TData = Awaited<ReturnType<typeof listComments>>, TError = ListComments400 | ListComments401 | ListComments403 | ListComments404 | ListComments409 | ListComments422 | ListComments500>(postId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsQueryKey(postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listComments>>> = ({ signal }) => listComments(postId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof listComments>>>
export type ListCommentsQueryError = ListComments400 | ListComments401 | ListComments403 | ListComments404 | ListComments409 | ListComments422 | ListComments500


/**
 * @summary list
 */

export function createListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = ListComments400 | ListComments401 | ListComments403 | ListComments404 | ListComments409 | ListComments422 | ListComments500>(
 postId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCommentsQueryOptions(postId,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Comments Endpoints
 * @summary show
 */
export const getCommentsShowByCommentId = (
    commentId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCommentsShowByCommentId200>(
      {url: `http://localhost:4000/comments/show/${commentId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCommentsShowByCommentIdQueryKey = (commentId?: number,) => {
    return [
    `http://localhost:4000/comments/show/${commentId}`
    ] as const;
    }

    
export const getGetCommentsShowByCommentIdQueryOptions = <TData = Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError = GetCommentsShowByCommentId400 | GetCommentsShowByCommentId401 | GetCommentsShowByCommentId403 | GetCommentsShowByCommentId404 | GetCommentsShowByCommentId409 | GetCommentsShowByCommentId422 | GetCommentsShowByCommentId500>(commentId: number, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCommentsShowByCommentIdQueryKey(commentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommentsShowByCommentId>>> = ({ signal }) => getCommentsShowByCommentId(commentId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(commentId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommentsShowByCommentIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCommentsShowByCommentId>>>
export type GetCommentsShowByCommentIdQueryError = GetCommentsShowByCommentId400 | GetCommentsShowByCommentId401 | GetCommentsShowByCommentId403 | GetCommentsShowByCommentId404 | GetCommentsShowByCommentId409 | GetCommentsShowByCommentId422 | GetCommentsShowByCommentId500


/**
 * @summary show
 */

export function createGetCommentsShowByCommentId<TData = Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError = GetCommentsShowByCommentId400 | GetCommentsShowByCommentId401 | GetCommentsShowByCommentId403 | GetCommentsShowByCommentId404 | GetCommentsShowByCommentId409 | GetCommentsShowByCommentId422 | GetCommentsShowByCommentId500>(
 commentId: number, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCommentsShowByCommentIdQueryOptions(commentId,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Comments Endpoints
 * @summary update
 */
export const patchCommentsByCommentId = (
    commentId: number,
    patchCommentsByCommentIdBody: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PatchCommentsByCommentId200>(
      {url: `http://localhost:4000/comments/${commentId}`, method: 'PATCH',
      data: patchCommentsByCommentIdBody
    },
      options);
    }
  


export const getPatchCommentsByCommentIdMutationOptions = <TError = PatchCommentsByCommentId400 | PatchCommentsByCommentId401 | PatchCommentsByCommentId403 | PatchCommentsByCommentId404 | PatchCommentsByCommentId409 | PatchCommentsByCommentId422 | PatchCommentsByCommentId500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof patchCommentsByCommentId>>, TError,{commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof patchCommentsByCommentId>>, TError,{commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree}, TContext> => {

const mutationKey = ['patchCommentsByCommentId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchCommentsByCommentId>>, {commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree}> = (props) => {
          const {commentId,data} = props ?? {};

          return  patchCommentsByCommentId(commentId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchCommentsByCommentIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchCommentsByCommentId>>>
    export type PatchCommentsByCommentIdMutationBody = PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree
    export type PatchCommentsByCommentIdMutationError = PatchCommentsByCommentId400 | PatchCommentsByCommentId401 | PatchCommentsByCommentId403 | PatchCommentsByCommentId404 | PatchCommentsByCommentId409 | PatchCommentsByCommentId422 | PatchCommentsByCommentId500

    /**
 * @summary update
 */
export const createPatchCommentsByCommentId = <TError = PatchCommentsByCommentId400 | PatchCommentsByCommentId401 | PatchCommentsByCommentId403 | PatchCommentsByCommentId404 | PatchCommentsByCommentId409 | PatchCommentsByCommentId422 | PatchCommentsByCommentId500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof patchCommentsByCommentId>>, TError,{commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof patchCommentsByCommentId>>,
        TError,
        {commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree},
        TContext
      > => {

      const mutationOptions = getPatchCommentsByCommentIdMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * Comments Endpoints
 * @summary remove
 */
export const deleteCommentsByCommentId = (
    commentId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteCommentsByCommentId200>(
      {url: `http://localhost:4000/comments/${commentId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCommentsByCommentIdMutationOptions = <TError = DeleteCommentsByCommentId400 | DeleteCommentsByCommentId401 | DeleteCommentsByCommentId403 | DeleteCommentsByCommentId404 | DeleteCommentsByCommentId409 | DeleteCommentsByCommentId422 | DeleteCommentsByCommentId500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteCommentsByCommentId>>, TError,{commentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteCommentsByCommentId>>, TError,{commentId: number}, TContext> => {

const mutationKey = ['deleteCommentsByCommentId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCommentsByCommentId>>, {commentId: number}> = (props) => {
          const {commentId} = props ?? {};

          return  deleteCommentsByCommentId(commentId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCommentsByCommentIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCommentsByCommentId>>>
    
    export type DeleteCommentsByCommentIdMutationError = DeleteCommentsByCommentId400 | DeleteCommentsByCommentId401 | DeleteCommentsByCommentId403 | DeleteCommentsByCommentId404 | DeleteCommentsByCommentId409 | DeleteCommentsByCommentId422 | DeleteCommentsByCommentId500

    /**
 * @summary remove
 */
export const createDeleteCommentsByCommentId = <TError = DeleteCommentsByCommentId400 | DeleteCommentsByCommentId401 | DeleteCommentsByCommentId403 | DeleteCommentsByCommentId404 | DeleteCommentsByCommentId409 | DeleteCommentsByCommentId422 | DeleteCommentsByCommentId500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteCommentsByCommentId>>, TError,{commentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteCommentsByCommentId>>,
        TError,
        {commentId: number},
        TContext
      > => {

      const mutationOptions = getDeleteCommentsByCommentIdMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    