/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddComment200,
  AddComment400,
  AddComment401,
  AddComment403,
  AddComment404,
  AddComment409,
  AddComment422,
  AddComment500,
  AddCommentBodyOne,
  AddCommentBodyThree,
  AddCommentBodyTwo,
  DeleteCommentsByCommentId200,
  DeleteCommentsByCommentId400,
  DeleteCommentsByCommentId401,
  DeleteCommentsByCommentId403,
  DeleteCommentsByCommentId404,
  DeleteCommentsByCommentId409,
  DeleteCommentsByCommentId422,
  DeleteCommentsByCommentId500,
  GetCommentsShowByCommentId200,
  GetCommentsShowByCommentId400,
  GetCommentsShowByCommentId401,
  GetCommentsShowByCommentId403,
  GetCommentsShowByCommentId404,
  GetCommentsShowByCommentId409,
  GetCommentsShowByCommentId422,
  GetCommentsShowByCommentId500,
  ListComments200,
  ListComments400,
  ListComments401,
  ListComments403,
  ListComments404,
  ListComments409,
  ListComments422,
  ListComments500,
  PatchCommentsByCommentId200,
  PatchCommentsByCommentId400,
  PatchCommentsByCommentId401,
  PatchCommentsByCommentId403,
  PatchCommentsByCommentId404,
  PatchCommentsByCommentId409,
  PatchCommentsByCommentId422,
  PatchCommentsByCommentId500,
  PatchCommentsByCommentIdBodyOne,
  PatchCommentsByCommentIdBodyThree,
  PatchCommentsByCommentIdBodyTwo
} from '.././schemas';





/**
 * add new commnet for this post
 * @summary add
 */
export const addComment = (
    postId: string,
    addCommentBody: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AddComment200>> => {
    
    
    return axios.post(
      `http://localhost:4000/comments/${postId}`,
      addCommentBody,options
    );
  }



export const getAddCommentMutationOptions = <TError = AxiosError<AddComment400 | AddComment401 | AddComment403 | AddComment404 | AddComment409 | AddComment422 | AddComment500>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree}, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree}, TContext> => {

const mutationKey = ['addComment'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addComment>>, {postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree}> = (props) => {
          const {postId,data} = props ?? {};

          return  addComment(postId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddCommentMutationResult = NonNullable<Awaited<ReturnType<typeof addComment>>>
    export type AddCommentMutationBody = AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree
    export type AddCommentMutationError = AxiosError<AddComment400 | AddComment401 | AddComment403 | AddComment404 | AddComment409 | AddComment422 | AddComment500>

    /**
 * @summary add
 */
export const createAddComment = <TError = AxiosError<AddComment400 | AddComment401 | AddComment403 | AddComment404 | AddComment409 | AddComment422 | AddComment500>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof addComment>>,
        TError,
        {postId: string;data: AddCommentBodyOne | AddCommentBodyTwo | AddCommentBodyThree},
        TContext
      > => {

      const mutationOptions = getAddCommentMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * list comments of a post
 * @summary list
 */
export const listComments = (
    postId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListComments200>> => {
    
    
    return axios.get(
      `http://localhost:4000/comments/${postId}`,options
    );
  }




export const getListCommentsQueryKey = (postId?: string,) => {
    return [
    `http://localhost:4000/comments/${postId}`
    ] as const;
    }

    
export const getListCommentsQueryOptions = <TData = Awaited<ReturnType<typeof listComments>>, TError = AxiosError<ListComments400 | ListComments401 | ListComments403 | ListComments404 | ListComments409 | ListComments422 | ListComments500>>(postId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsQueryKey(postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listComments>>> = ({ signal }) => listComments(postId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof listComments>>>
export type ListCommentsQueryError = AxiosError<ListComments400 | ListComments401 | ListComments403 | ListComments404 | ListComments409 | ListComments422 | ListComments500>


/**
 * @summary list
 */

export function createListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = AxiosError<ListComments400 | ListComments401 | ListComments403 | ListComments404 | ListComments409 | ListComments422 | ListComments500>>(
 postId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCommentsQueryOptions(postId,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Comments Endpoints
 * @summary show
 */
export const getCommentsShowByCommentId = (
    commentId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetCommentsShowByCommentId200>> => {
    
    
    return axios.get(
      `http://localhost:4000/comments/show/${commentId}`,options
    );
  }




export const getGetCommentsShowByCommentIdQueryKey = (commentId?: number,) => {
    return [
    `http://localhost:4000/comments/show/${commentId}`
    ] as const;
    }

    
export const getGetCommentsShowByCommentIdQueryOptions = <TData = Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError = AxiosError<GetCommentsShowByCommentId400 | GetCommentsShowByCommentId401 | GetCommentsShowByCommentId403 | GetCommentsShowByCommentId404 | GetCommentsShowByCommentId409 | GetCommentsShowByCommentId422 | GetCommentsShowByCommentId500>>(commentId: number, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCommentsShowByCommentIdQueryKey(commentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommentsShowByCommentId>>> = ({ signal }) => getCommentsShowByCommentId(commentId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(commentId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommentsShowByCommentIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCommentsShowByCommentId>>>
export type GetCommentsShowByCommentIdQueryError = AxiosError<GetCommentsShowByCommentId400 | GetCommentsShowByCommentId401 | GetCommentsShowByCommentId403 | GetCommentsShowByCommentId404 | GetCommentsShowByCommentId409 | GetCommentsShowByCommentId422 | GetCommentsShowByCommentId500>


/**
 * @summary show
 */

export function createGetCommentsShowByCommentId<TData = Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError = AxiosError<GetCommentsShowByCommentId400 | GetCommentsShowByCommentId401 | GetCommentsShowByCommentId403 | GetCommentsShowByCommentId404 | GetCommentsShowByCommentId409 | GetCommentsShowByCommentId422 | GetCommentsShowByCommentId500>>(
 commentId: number, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getCommentsShowByCommentId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCommentsShowByCommentIdQueryOptions(commentId,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Comments Endpoints
 * @summary update
 */
export const patchCommentsByCommentId = (
    commentId: number,
    patchCommentsByCommentIdBody: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PatchCommentsByCommentId200>> => {
    
    
    return axios.patch(
      `http://localhost:4000/comments/${commentId}`,
      patchCommentsByCommentIdBody,options
    );
  }



export const getPatchCommentsByCommentIdMutationOptions = <TError = AxiosError<PatchCommentsByCommentId400 | PatchCommentsByCommentId401 | PatchCommentsByCommentId403 | PatchCommentsByCommentId404 | PatchCommentsByCommentId409 | PatchCommentsByCommentId422 | PatchCommentsByCommentId500>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof patchCommentsByCommentId>>, TError,{commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree}, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof patchCommentsByCommentId>>, TError,{commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree}, TContext> => {

const mutationKey = ['patchCommentsByCommentId'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchCommentsByCommentId>>, {commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree}> = (props) => {
          const {commentId,data} = props ?? {};

          return  patchCommentsByCommentId(commentId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchCommentsByCommentIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchCommentsByCommentId>>>
    export type PatchCommentsByCommentIdMutationBody = PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree
    export type PatchCommentsByCommentIdMutationError = AxiosError<PatchCommentsByCommentId400 | PatchCommentsByCommentId401 | PatchCommentsByCommentId403 | PatchCommentsByCommentId404 | PatchCommentsByCommentId409 | PatchCommentsByCommentId422 | PatchCommentsByCommentId500>

    /**
 * @summary update
 */
export const createPatchCommentsByCommentId = <TError = AxiosError<PatchCommentsByCommentId400 | PatchCommentsByCommentId401 | PatchCommentsByCommentId403 | PatchCommentsByCommentId404 | PatchCommentsByCommentId409 | PatchCommentsByCommentId422 | PatchCommentsByCommentId500>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof patchCommentsByCommentId>>, TError,{commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof patchCommentsByCommentId>>,
        TError,
        {commentId: number;data: PatchCommentsByCommentIdBodyOne | PatchCommentsByCommentIdBodyTwo | PatchCommentsByCommentIdBodyThree},
        TContext
      > => {

      const mutationOptions = getPatchCommentsByCommentIdMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * Comments Endpoints
 * @summary remove
 */
export const deleteCommentsByCommentId = (
    commentId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteCommentsByCommentId200>> => {
    
    
    return axios.delete(
      `http://localhost:4000/comments/${commentId}`,options
    );
  }



export const getDeleteCommentsByCommentIdMutationOptions = <TError = AxiosError<DeleteCommentsByCommentId400 | DeleteCommentsByCommentId401 | DeleteCommentsByCommentId403 | DeleteCommentsByCommentId404 | DeleteCommentsByCommentId409 | DeleteCommentsByCommentId422 | DeleteCommentsByCommentId500>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteCommentsByCommentId>>, TError,{commentId: number}, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteCommentsByCommentId>>, TError,{commentId: number}, TContext> => {

const mutationKey = ['deleteCommentsByCommentId'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCommentsByCommentId>>, {commentId: number}> = (props) => {
          const {commentId} = props ?? {};

          return  deleteCommentsByCommentId(commentId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCommentsByCommentIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCommentsByCommentId>>>
    
    export type DeleteCommentsByCommentIdMutationError = AxiosError<DeleteCommentsByCommentId400 | DeleteCommentsByCommentId401 | DeleteCommentsByCommentId403 | DeleteCommentsByCommentId404 | DeleteCommentsByCommentId409 | DeleteCommentsByCommentId422 | DeleteCommentsByCommentId500>

    /**
 * @summary remove
 */
export const createDeleteCommentsByCommentId = <TError = AxiosError<DeleteCommentsByCommentId400 | DeleteCommentsByCommentId401 | DeleteCommentsByCommentId403 | DeleteCommentsByCommentId404 | DeleteCommentsByCommentId409 | DeleteCommentsByCommentId422 | DeleteCommentsByCommentId500>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteCommentsByCommentId>>, TError,{commentId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteCommentsByCommentId>>,
        TError,
        {commentId: number},
        TContext
      > => {

      const mutationOptions = getDeleteCommentsByCommentIdMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    