/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  AuthLogin200,
  AuthLogin400,
  AuthLogin401,
  AuthLogin403,
  AuthLogin404,
  AuthLogin409,
  AuthLogin422,
  AuthLogin500,
  AuthLoginBodyOne,
  AuthLoginBodyThree,
  AuthLoginBodyTwo,
  AuthMe200,
  AuthMe400,
  AuthMe401,
  AuthMe403,
  AuthMe404,
  AuthMe409,
  AuthMe422,
  AuthMe500,
  AuthRefreshTokens200,
  AuthRefreshTokensBodyOne,
  AuthRefreshTokensBodyThree,
  AuthRefreshTokensBodyTwo,
  AuthRegister200,
  AuthRegisterBodyOne,
  AuthRegisterBodyThree,
  AuthRegisterBodyTwo
} from '.././schemas';

import { customInstance } from '../../custom-instance';




/**
 * login users to thier account
 * @summary login
 */
export const authLogin = (
    authLoginBody: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthLogin200>(
      {url: `http://localhost:4000/auth/login`, method: 'POST',
      data: authLoginBody, signal
    },
      );
    }
  


export const getAuthLoginMutationOptions = <TError = AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext> => {

const mutationKey = ['authLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogin>>, {data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  authLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
    export type AuthLoginMutationBody = AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree
    export type AuthLoginMutationError = AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500

    /**
 * @summary login
 */
export const createAuthLogin = <TError = AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authLogin>>,
        TError,
        {data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree},
        TContext
      > => {

      const mutationOptions = getAuthLoginMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * register new account
 * @summary register
 */
export const authRegister = (
    authRegisterBody: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthRegister200>(
      {url: `http://localhost:4000/auth/register`, method: 'POST',
      data: authRegisterBody, signal
    },
      );
    }
  


export const getAuthRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext> => {

const mutationKey = ['authRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRegister>>, {data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  authRegister(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authRegister>>>
    export type AuthRegisterMutationBody = AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree
    export type AuthRegisterMutationError = unknown

    /**
 * @summary register
 */
export const createAuthRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authRegister>>,
        TError,
        {data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree},
        TContext
      > => {

      const mutationOptions = getAuthRegisterMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * get current logged in user details
 * @summary me
 */
export const authMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthMe200>(
      {url: `http://localhost:4000/auth/me`, method: 'GET', signal
    },
      );
    }
  



export const getAuthMeQueryKey = () => {
    return [
    `http://localhost:4000/auth/me`
    ] as const;
    }

    
export const getAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof authMe>>, TError = AuthMe400 | AuthMe401 | AuthMe403 | AuthMe404 | AuthMe409 | AuthMe422 | AuthMe500>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({ signal }) => authMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
export type AuthMeQueryError = AuthMe400 | AuthMe401 | AuthMe403 | AuthMe404 | AuthMe409 | AuthMe422 | AuthMe500


/**
 * @summary me
 */

export function createAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = AuthMe400 | AuthMe401 | AuthMe403 | AuthMe404 | AuthMe409 | AuthMe422 | AuthMe500>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthMeQueryOptions(options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * refresh access and refresh tokens
 * @summary refresh
 */
export const authRefreshTokens = (
    authRefreshTokensBody: AuthRefreshTokensBodyOne | AuthRefreshTokensBodyTwo | AuthRefreshTokensBodyThree,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthRefreshTokens200>(
      {url: `http://localhost:4000/auth/refresh`, method: 'POST',
      data: authRefreshTokensBody, signal
    },
      );
    }
  


export const getAuthRefreshTokensMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError,{data: AuthRefreshTokensBodyOne | AuthRefreshTokensBodyTwo | AuthRefreshTokensBodyThree}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError,{data: AuthRefreshTokensBodyOne | AuthRefreshTokensBodyTwo | AuthRefreshTokensBodyThree}, TContext> => {

const mutationKey = ['authRefreshTokens'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRefreshTokens>>, {data: AuthRefreshTokensBodyOne | AuthRefreshTokensBodyTwo | AuthRefreshTokensBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  authRefreshTokens(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthRefreshTokensMutationResult = NonNullable<Awaited<ReturnType<typeof authRefreshTokens>>>
    export type AuthRefreshTokensMutationBody = AuthRefreshTokensBodyOne | AuthRefreshTokensBodyTwo | AuthRefreshTokensBodyThree
    export type AuthRefreshTokensMutationError = unknown

    /**
 * @summary refresh
 */
export const createAuthRefreshTokens = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError,{data: AuthRefreshTokensBodyOne | AuthRefreshTokensBodyTwo | AuthRefreshTokensBodyThree}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authRefreshTokens>>,
        TError,
        {data: AuthRefreshTokensBodyOne | AuthRefreshTokensBodyTwo | AuthRefreshTokensBodyThree},
        TContext
      > => {

      const mutationOptions = getAuthRefreshTokensMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    