/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';


/**
 * login users to thier account
 * @summary login
 */
export const authLoginBody = zod.object({
  "email": zod.email(),
  "password": zod.string()
})

/**
 * register new account
 * @summary register
 */
export const authRegisterBody = zod.object({
  "email": zod.email(),
  "password": zod.string(),
  "username": zod.string(),
  "name": zod.string()
})

/**
 * refresh access and refresh tokens
 * @summary refresh
 */
export const authRefreshTokensBody = zod.object({
  "refreshToken": zod.string()
})

