/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthLogin200,
  AuthLogin400,
  AuthLogin401,
  AuthLogin403,
  AuthLogin404,
  AuthLogin409,
  AuthLogin422,
  AuthLogin500,
  AuthLoginBodyOne,
  AuthLoginBodyThree,
  AuthLoginBodyTwo,
  AuthLogout200,
  AuthMe200,
  AuthRefreshTokens200,
  AuthRegister200,
  AuthRegisterBodyOne,
  AuthRegisterBodyThree,
  AuthRegisterBodyTwo
} from '.././schemas';





/**
 * login users to thier account
 * @summary login
 */
export const authLogin = (
    authLoginBody: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthLogin200>> => {
    
    
    return axios.post(
      `http://localhost:4000/auth/login`,
      authLoginBody,options
    );
  }



export const getAuthLoginMutationOptions = <TError = AxiosError<AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext> => {

const mutationKey = ['authLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogin>>, {data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  authLogin(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
    export type AuthLoginMutationBody = AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree
    export type AuthLoginMutationError = AxiosError<AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500>

    /**
 * @summary login
 */
export const createAuthLogin = <TError = AxiosError<AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authLogin>>,
        TError,
        {data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree},
        TContext
      > => {

      const mutationOptions = getAuthLoginMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * register new account
 * @summary register
 */
export const authRegister = (
    authRegisterBody: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthRegister200>> => {
    
    
    return axios.post(
      `http://localhost:4000/auth/register`,
      authRegisterBody,options
    );
  }



export const getAuthRegisterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext> => {

const mutationKey = ['authRegister'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRegister>>, {data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  authRegister(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authRegister>>>
    export type AuthRegisterMutationBody = AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree
    export type AuthRegisterMutationError = AxiosError<unknown>

    /**
 * @summary register
 */
export const createAuthRegister = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authRegister>>,
        TError,
        {data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree},
        TContext
      > => {

      const mutationOptions = getAuthRegisterMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * get current logged in user details
 * @summary me
 */
export const authMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthMe200>> => {
    
    
    return axios.post(
      `http://localhost:4000/auth/me`,undefined,options
    );
  }



export const getAuthMeMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authMe>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof authMe>>, TError,void, TContext> => {

const mutationKey = ['authMe'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authMe>>, void> = () => {
          

          return  authMe(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthMeMutationResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
    
    export type AuthMeMutationError = AxiosError<unknown>

    /**
 * @summary me
 */
export const createAuthMe = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authMe>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authMe>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthMeMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * logout user from the account
 * @summary Logout
 */
export const authLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthLogout200>> => {
    
    
    return axios.post(
      `http://localhost:4000/auth/logout`,undefined,options
    );
  }



export const getAuthLogoutMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogout'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {
          

          return  authLogout(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>
    
    export type AuthLogoutMutationError = AxiosError<unknown>

    /**
 * @summary Logout
 */
export const createAuthLogout = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthLogoutMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * refresh access and refresh tokens
 * @summary refresh
 */
export const authRefreshTokens = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthRefreshTokens200>> => {
    
    
    return axios.get(
      `http://localhost:4000/auth/refresh`,options
    );
  }




export const getAuthRefreshTokensQueryKey = () => {
    return [
    `http://localhost:4000/auth/refresh`
    ] as const;
    }

    
export const getAuthRefreshTokensQueryOptions = <TData = Awaited<ReturnType<typeof authRefreshTokens>>, TError = AxiosError<unknown>>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthRefreshTokensQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authRefreshTokens>>> = ({ signal }) => authRefreshTokens({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthRefreshTokensQueryResult = NonNullable<Awaited<ReturnType<typeof authRefreshTokens>>>
export type AuthRefreshTokensQueryError = AxiosError<unknown>


/**
 * @summary refresh
 */

export function createAuthRefreshTokens<TData = Awaited<ReturnType<typeof authRefreshTokens>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthRefreshTokensQueryOptions(options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




