/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  AuthLogin200,
  AuthLogin400,
  AuthLogin401,
  AuthLogin403,
  AuthLogin404,
  AuthLogin409,
  AuthLogin422,
  AuthLogin500,
  AuthLoginBodyOne,
  AuthLoginBodyThree,
  AuthLoginBodyTwo,
  AuthLogout200,
  AuthMe200,
  AuthMe400,
  AuthMe401,
  AuthMe403,
  AuthMe404,
  AuthMe409,
  AuthMe422,
  AuthMe500,
  AuthRefreshTokens200,
  AuthRegister200,
  AuthRegisterBodyOne,
  AuthRegisterBodyThree,
  AuthRegisterBodyTwo
} from '.././schemas';

import { customInstance } from '../../custom-instance';




/**
 * login users to thier account
 * @summary login
 */
export const authLogin = (
    authLoginBody: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthLogin200>(
      {url: `http://localhost:4000/auth/login`, method: 'POST',
      data: authLoginBody, signal
    },
      );
    }
  


export const getAuthLoginMutationOptions = <TError = AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext> => {

const mutationKey = ['authLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogin>>, {data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  authLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>
    export type AuthLoginMutationBody = AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree
    export type AuthLoginMutationError = AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500

    /**
 * @summary login
 */
export const createAuthLogin = <TError = AuthLogin400 | AuthLogin401 | AuthLogin403 | AuthLogin404 | AuthLogin409 | AuthLogin422 | AuthLogin500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogin>>, TError,{data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authLogin>>,
        TError,
        {data: AuthLoginBodyOne | AuthLoginBodyTwo | AuthLoginBodyThree},
        TContext
      > => {

      const mutationOptions = getAuthLoginMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * register new account
 * @summary register
 */
export const authRegister = (
    authRegisterBody: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthRegister200>(
      {url: `http://localhost:4000/auth/register`, method: 'POST',
      data: authRegisterBody, signal
    },
      );
    }
  


export const getAuthRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext> => {

const mutationKey = ['authRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRegister>>, {data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  authRegister(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authRegister>>>
    export type AuthRegisterMutationBody = AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree
    export type AuthRegisterMutationError = unknown

    /**
 * @summary register
 */
export const createAuthRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authRegister>>, TError,{data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authRegister>>,
        TError,
        {data: AuthRegisterBodyOne | AuthRegisterBodyTwo | AuthRegisterBodyThree},
        TContext
      > => {

      const mutationOptions = getAuthRegisterMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * get current logged in user details
 * @summary me
 */
export const authMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthMe200>(
      {url: `http://localhost:4000/auth/me`, method: 'POST', signal
    },
      );
    }
  


export const getAuthMeMutationOptions = <TError = AuthMe400 | AuthMe401 | AuthMe403 | AuthMe404 | AuthMe409 | AuthMe422 | AuthMe500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authMe>>, TError,void, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof authMe>>, TError,void, TContext> => {

const mutationKey = ['authMe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authMe>>, void> = () => {
          

          return  authMe()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthMeMutationResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
    
    export type AuthMeMutationError = AuthMe400 | AuthMe401 | AuthMe403 | AuthMe404 | AuthMe409 | AuthMe422 | AuthMe500

    /**
 * @summary me
 */
export const createAuthMe = <TError = AuthMe400 | AuthMe401 | AuthMe403 | AuthMe404 | AuthMe409 | AuthMe422 | AuthMe500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authMe>>, TError,void, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authMe>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthMeMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * logout user from the account
 * @summary Logout
 */
export const authLogout = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthLogout200>(
      {url: `http://localhost:4000/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getAuthLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {
          

          return  authLogout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>
    
    export type AuthLogoutMutationError = unknown

    /**
 * @summary Logout
 */
export const createAuthLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthLogoutMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * refresh access and refresh tokens
 * @summary refresh
 */
export const authRefreshTokens = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthRefreshTokens200>(
      {url: `http://localhost:4000/auth/refresh`, method: 'GET', signal
    },
      );
    }
  



export const getAuthRefreshTokensQueryKey = () => {
    return [
    `http://localhost:4000/auth/refresh`
    ] as const;
    }

    
export const getAuthRefreshTokensQueryOptions = <TData = Awaited<ReturnType<typeof authRefreshTokens>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthRefreshTokensQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authRefreshTokens>>> = ({ signal }) => authRefreshTokens(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthRefreshTokensQueryResult = NonNullable<Awaited<ReturnType<typeof authRefreshTokens>>>
export type AuthRefreshTokensQueryError = unknown


/**
 * @summary refresh
 */

export function createAuthRefreshTokens<TData = Awaited<ReturnType<typeof authRefreshTokens>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof authRefreshTokens>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthRefreshTokensQueryOptions(options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




