/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetUsersShowByUserId200,
  GetUsersShowByUserId400,
  GetUsersShowByUserId401,
  GetUsersShowByUserId403,
  GetUsersShowByUserId404,
  GetUsersShowByUserId409,
  GetUsersShowByUserId422,
  GetUsersShowByUserId500
} from '.././schemas';





/**
 * Users Endpoints
 * @summary show
 */
export const getUsersShowByUserId = (
    userId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetUsersShowByUserId200>> => {
    
    
    return axios.get(
      `http://localhost:4000/users/show/${userId}`,options
    );
  }




export const getGetUsersShowByUserIdQueryKey = (userId?: string,) => {
    return [
    `http://localhost:4000/users/show/${userId}`
    ] as const;
    }

    
export const getGetUsersShowByUserIdQueryOptions = <TData = Awaited<ReturnType<typeof getUsersShowByUserId>>, TError = AxiosError<GetUsersShowByUserId400 | GetUsersShowByUserId401 | GetUsersShowByUserId403 | GetUsersShowByUserId404 | GetUsersShowByUserId409 | GetUsersShowByUserId422 | GetUsersShowByUserId500>>(userId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getUsersShowByUserId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersShowByUserIdQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersShowByUserId>>> = ({ signal }) => getUsersShowByUserId(userId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getUsersShowByUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersShowByUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersShowByUserId>>>
export type GetUsersShowByUserIdQueryError = AxiosError<GetUsersShowByUserId400 | GetUsersShowByUserId401 | GetUsersShowByUserId403 | GetUsersShowByUserId404 | GetUsersShowByUserId409 | GetUsersShowByUserId422 | GetUsersShowByUserId500>


/**
 * @summary show
 */

export function createGetUsersShowByUserId<TData = Awaited<ReturnType<typeof getUsersShowByUserId>>, TError = AxiosError<GetUsersShowByUserId400 | GetUsersShowByUserId401 | GetUsersShowByUserId403 | GetUsersShowByUserId404 | GetUsersShowByUserId409 | GetUsersShowByUserId422 | GetUsersShowByUserId500>>(
 userId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getUsersShowByUserId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersShowByUserIdQueryOptions(userId,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




