/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';


/**
 * Users Endpoints
 * @summary show
 */
export const getUsersShowByUserIdParams = zod.object({
  "userId": zod.uuid()
})

