/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  AddPost200,
  AddPost400,
  AddPost401,
  AddPost403,
  AddPost404,
  AddPost409,
  AddPost422,
  AddPost500,
  AddPostBodyOne,
  AddPostBodyThree,
  AddPostBodyTwo,
  ListPosts200,
  ListPosts400,
  ListPosts401,
  ListPosts403,
  ListPosts404,
  ListPosts409,
  ListPosts422,
  ListPosts500,
  ListPostsParams,
  RemovePost200,
  RemovePost400,
  RemovePost401,
  RemovePost403,
  RemovePost404,
  RemovePost409,
  RemovePost422,
  RemovePost500,
  ShowPost200,
  ShowPost400,
  ShowPost401,
  ShowPost403,
  ShowPost404,
  ShowPost409,
  ShowPost422,
  ShowPost500,
  UpdatePost200,
  UpdatePost400,
  UpdatePost401,
  UpdatePost403,
  UpdatePost404,
  UpdatePost409,
  UpdatePost422,
  UpdatePost500,
  UpdatePostBodyOne,
  UpdatePostBodyThree,
  UpdatePostBodyTwo
} from '.././schemas';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * add new post
 * @summary add
 */
export const addPost = (
    addPostBody: AddPostBodyOne | AddPostBodyTwo | AddPostBodyThree,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AddPost200>(
      {url: `http://localhost:4000/posts/add`, method: 'POST',
      data: addPostBody, signal
    },
      options);
    }
  


export const getAddPostMutationOptions = <TError = AddPost400 | AddPost401 | AddPost403 | AddPost404 | AddPost409 | AddPost422 | AddPost500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof addPost>>, TError,{data: AddPostBodyOne | AddPostBodyTwo | AddPostBodyThree}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof addPost>>, TError,{data: AddPostBodyOne | AddPostBodyTwo | AddPostBodyThree}, TContext> => {

const mutationKey = ['addPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addPost>>, {data: AddPostBodyOne | AddPostBodyTwo | AddPostBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  addPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddPostMutationResult = NonNullable<Awaited<ReturnType<typeof addPost>>>
    export type AddPostMutationBody = AddPostBodyOne | AddPostBodyTwo | AddPostBodyThree
    export type AddPostMutationError = AddPost400 | AddPost401 | AddPost403 | AddPost404 | AddPost409 | AddPost422 | AddPost500

    /**
 * @summary add
 */
export const createAddPost = <TError = AddPost400 | AddPost401 | AddPost403 | AddPost404 | AddPost409 | AddPost422 | AddPost500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof addPost>>, TError,{data: AddPostBodyOne | AddPostBodyTwo | AddPostBodyThree}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof addPost>>,
        TError,
        {data: AddPostBodyOne | AddPostBodyTwo | AddPostBodyThree},
        TContext
      > => {

      const mutationOptions = getAddPostMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * list posts
 * @summary list
 */
export const listPosts = (
    params: ListPostsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListPosts200>(
      {url: `http://localhost:4000/posts/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListPostsQueryKey = (params?: ListPostsParams,) => {
    return [
    `http://localhost:4000/posts/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListPostsQueryOptions = <TData = Awaited<ReturnType<typeof listPosts>>, TError = ListPosts400 | ListPosts401 | ListPosts403 | ListPosts404 | ListPosts409 | ListPosts422 | ListPosts500>(params: ListPostsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPosts>>> = ({ signal }) => listPosts(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostsQueryResult = NonNullable<Awaited<ReturnType<typeof listPosts>>>
export type ListPostsQueryError = ListPosts400 | ListPosts401 | ListPosts403 | ListPosts404 | ListPosts409 | ListPosts422 | ListPosts500


/**
 * @summary list
 */

export function createListPosts<TData = Awaited<ReturnType<typeof listPosts>>, TError = ListPosts400 | ListPosts401 | ListPosts403 | ListPosts404 | ListPosts409 | ListPosts422 | ListPosts500>(
 params: ListPostsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPostsQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * show post
 * @summary show
 */
export const showPost = (
    postId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ShowPost200>(
      {url: `http://localhost:4000/posts/${postId}`, method: 'GET', signal
    },
      options);
    }
  



export const getShowPostQueryKey = (postId?: string,) => {
    return [
    `http://localhost:4000/posts/${postId}`
    ] as const;
    }

    
export const getShowPostQueryOptions = <TData = Awaited<ReturnType<typeof showPost>>, TError = ShowPost400 | ShowPost401 | ShowPost403 | ShowPost404 | ShowPost409 | ShowPost422 | ShowPost500>(postId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showPost>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowPostQueryKey(postId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof showPost>>> = ({ signal }) => showPost(postId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof showPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowPostQueryResult = NonNullable<Awaited<ReturnType<typeof showPost>>>
export type ShowPostQueryError = ShowPost400 | ShowPost401 | ShowPost403 | ShowPost404 | ShowPost409 | ShowPost422 | ShowPost500


/**
 * @summary show
 */

export function createShowPost<TData = Awaited<ReturnType<typeof showPost>>, TError = ShowPost400 | ShowPost401 | ShowPost403 | ShowPost404 | ShowPost409 | ShowPost422 | ShowPost500>(
 postId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof showPost>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowPostQueryOptions(postId,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * update post
 * @summary update
 */
export const updatePost = (
    postId: string,
    updatePostBody: UpdatePostBodyOne | UpdatePostBodyTwo | UpdatePostBodyThree,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdatePost200>(
      {url: `http://localhost:4000/posts/${postId}`, method: 'PATCH',
      data: updatePostBody
    },
      options);
    }
  


export const getUpdatePostMutationOptions = <TError = UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost409 | UpdatePost422 | UpdatePost500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{postId: string;data: UpdatePostBodyOne | UpdatePostBodyTwo | UpdatePostBodyThree}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{postId: string;data: UpdatePostBodyOne | UpdatePostBodyTwo | UpdatePostBodyThree}, TContext> => {

const mutationKey = ['updatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePost>>, {postId: string;data: UpdatePostBodyOne | UpdatePostBodyTwo | UpdatePostBodyThree}> = (props) => {
          const {postId,data} = props ?? {};

          return  updatePost(postId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof updatePost>>>
    export type UpdatePostMutationBody = UpdatePostBodyOne | UpdatePostBodyTwo | UpdatePostBodyThree
    export type UpdatePostMutationError = UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost409 | UpdatePost422 | UpdatePost500

    /**
 * @summary update
 */
export const createUpdatePost = <TError = UpdatePost400 | UpdatePost401 | UpdatePost403 | UpdatePost404 | UpdatePost409 | UpdatePost422 | UpdatePost500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{postId: string;data: UpdatePostBodyOne | UpdatePostBodyTwo | UpdatePostBodyThree}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof updatePost>>,
        TError,
        {postId: string;data: UpdatePostBodyOne | UpdatePostBodyTwo | UpdatePostBodyThree},
        TContext
      > => {

      const mutationOptions = getUpdatePostMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * remove post
 * @summary remove
 */
export const removePost = (
    postId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<RemovePost200>(
      {url: `http://localhost:4000/posts/${postId}`, method: 'DELETE'
    },
      options);
    }
  


export const getRemovePostMutationOptions = <TError = RemovePost400 | RemovePost401 | RemovePost403 | RemovePost404 | RemovePost409 | RemovePost422 | RemovePost500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removePost>>, TError,{postId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof removePost>>, TError,{postId: string}, TContext> => {

const mutationKey = ['removePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removePost>>, {postId: string}> = (props) => {
          const {postId} = props ?? {};

          return  removePost(postId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemovePostMutationResult = NonNullable<Awaited<ReturnType<typeof removePost>>>
    
    export type RemovePostMutationError = RemovePost400 | RemovePost401 | RemovePost403 | RemovePost404 | RemovePost409 | RemovePost422 | RemovePost500

    /**
 * @summary remove
 */
export const createRemovePost = <TError = RemovePost400 | RemovePost401 | RemovePost403 | RemovePost404 | RemovePost409 | RemovePost422 | RemovePost500,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof removePost>>, TError,{postId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof removePost>>,
        TError,
        {postId: string},
        TContext
      > => {

      const mutationOptions = getRemovePostMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    