/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';


/**
 * add new post
 * @summary add
 */
export const addPostBody = zod.object({
  "title": zod.string(),
  "content": zod.string(),
  "thumbnailUrl": zod.string().optional()
})

/**
 * list posts
 * @summary list
 */
export const listPostsQueryPageDefault = 1;export const listPostsQuerySizeDefault = 5;

export const listPostsQueryParams = zod.object({
  "page": zod.number(),
  "size": zod.number(),
  "userId": zod.uuid().optional()
})

/**
 * show post
 * @summary show
 */
export const showPostParams = zod.object({
  "postId": zod.uuid()
})

/**
 * update post
 * @summary update
 */
export const updatePostParams = zod.object({
  "postId": zod.uuid()
})

export const updatePostBody = zod.object({
  "title": zod.string(),
  "content": zod.string(),
  "thumbnailUrl": zod.string().optional()
})

/**
 * remove post
 * @summary remove
 */
export const removePostParams = zod.object({
  "postId": zod.string()
})

