/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AddComment200DataCreatedAt } from './addComment200DataCreatedAt';
import type { AddComment200DataUpdatedAt } from './addComment200DataUpdatedAt';

export type AddComment200Data = {
  id: number;
  message: string;
  userId: string;
  postId: string;
  createdAt: AddComment200DataCreatedAt;
  updatedAt: AddComment200DataUpdatedAt;
};
