/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AddPost200DataThumbnailUrl } from './addPost200DataThumbnailUrl';
import type { AddPost200DataCreatedAt } from './addPost200DataCreatedAt';
import type { AddPost200DataUpdatedAt } from './addPost200DataUpdatedAt';

export type AddPost200Data = {
  id: string;
  title: string;
  content: string;
  /** @nullable */
  thumbnailUrl: AddPost200DataThumbnailUrl;
  authorId: string;
  createdAt: AddPost200DataCreatedAt;
  updatedAt: AddPost200DataUpdatedAt;
};
