/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type AuthLogout200 = {
  success: boolean;
  message: string;
  data: null;
};
