/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AuthRegister200DataAvatarUrl } from './authRegister200DataAvatarUrl';
import type { AuthRegister200DataCreatedAt } from './authRegister200DataCreatedAt';
import type { AuthRegister200DataUpdatedAt } from './authRegister200DataUpdatedAt';

export type AuthRegister200Data = {
  id: string;
  email: string;
  name: string;
  username: string;
  /** @nullable */
  avatarUrl: AuthRegister200DataAvatarUrl;
  createdAt: AuthRegister200DataCreatedAt;
  updatedAt: AuthRegister200DataUpdatedAt;
};
