/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { AuthMe200DataAvatarUrl } from './authMe200DataAvatarUrl';
import type { AuthMe200DataCreatedAt } from './authMe200DataCreatedAt';
import type { AuthMe200DataUpdatedAt } from './authMe200DataUpdatedAt';

export type AuthMe200Data = {
  id: string;
  email: string;
  name: string;
  username: string;
  /** @nullable */
  avatarUrl: AuthMe200DataAvatarUrl;
  createdAt: AuthMe200DataCreatedAt;
  updatedAt: AuthMe200DataUpdatedAt;
};
