/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetUsersShowByUserId200DataAvatarUrl } from './getUsersShowByUserId200DataAvatarUrl';
import type { GetUsersShowByUserId200DataCreatedAt } from './getUsersShowByUserId200DataCreatedAt';
import type { GetUsersShowByUserId200DataUpdatedAt } from './getUsersShowByUserId200DataUpdatedAt';
import type { _GetUsersShowByUserId200DataCount } from './_getUsersShowByUserId200DataCount';

export type GetUsersShowByUserId200Data = {
  id: string;
  email: string;
  name: string;
  username: string;
  /** @nullable */
  avatarUrl: GetUsersShowByUserId200DataAvatarUrl;
  createdAt: GetUsersShowByUserId200DataCreatedAt;
  updatedAt: GetUsersShowByUserId200DataUpdatedAt;
  _count: _GetUsersShowByUserId200DataCount;
};
