/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetUsersShowByUserId200Data } from './getUsersShowByUserId200Data';

export type GetUsersShowByUserId200 = {
  success: boolean;
  message: string;
  data: GetUsersShowByUserId200Data;
};
