/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListComments200DataItemCreatedAt } from './listComments200DataItemCreatedAt';
import type { ListComments200DataItemUpdatedAt } from './listComments200DataItemUpdatedAt';

export type ListComments200DataItem = {
  id: number;
  message: string;
  userId: string;
  postId: string;
  createdAt: ListComments200DataItemCreatedAt;
  updatedAt: ListComments200DataItemUpdatedAt;
};
