/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { ListPosts200DataItemThumbnailUrl } from './listPosts200DataItemThumbnailUrl';
import type { ListPosts200DataItemCreatedAt } from './listPosts200DataItemCreatedAt';
import type { ListPosts200DataItemUpdatedAt } from './listPosts200DataItemUpdatedAt';

export type ListPosts200DataItem = {
  id: string;
  title: string;
  content: string;
  /** @nullable */
  thumbnailUrl: ListPosts200DataItemThumbnailUrl;
  authorId: string;
  createdAt: ListPosts200DataItemCreatedAt;
  updatedAt: ListPosts200DataItemUpdatedAt;
};
