/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PatchCommentsByCommentId200DataCreatedAt } from './patchCommentsByCommentId200DataCreatedAt';
import type { PatchCommentsByCommentId200DataUpdatedAt } from './patchCommentsByCommentId200DataUpdatedAt';

export type PatchCommentsByCommentId200Data = {
  id: number;
  message: string;
  userId: string;
  postId: string;
  createdAt: PatchCommentsByCommentId200DataCreatedAt;
  updatedAt: PatchCommentsByCommentId200DataUpdatedAt;
};
