/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type RemovePost200DataThumbnailUrl = string | null | null;
